#!/usr/bin/env python3
"""
Interactive local setup assistant for FBS trading module.

Creates a local env file (default: .fbs_trading.env) without committing secrets.
"""

from __future__ import print_function

import getpass
import os
from pathlib import Path


def ask(prompt, default=None, secret=False, allow_empty=False):
    label = "{} [{}]: ".format(prompt, default) if default is not None else "{}: ".format(prompt)
    while True:
        value = getpass.getpass(label) if secret else input(label)
        value = value.strip()
        if value:
            return value
        if default is not None:
            return str(default)
        if allow_empty:
            return ""
        print("Value is required.")


def ask_bool(prompt, default=True):
    default_text = "y" if default else "n"
    raw = ask(prompt + " (y/n)", default=default_text).lower()
    return raw in ("y", "yes", "1", "true", "on")


def write_env(path, data):
    lines = [
        "# Auto-generated by scripts/fbs_setup_assistant.py",
        "# Do not commit this file.",
        "",
    ]
    order = [
        "FBS_PROFILE_PRESET",
        "FBS_SIMULATION_MODE",
        "FBS_DRY_RUN",
        "FBS_SYMBOL",
        "FBS_TIMEFRAME",
        "FBS_BARS",
        "FBS_RISK_PCT",
        "FBS_DEVIATION",
        "FBS_MAX_SPREAD_POINTS",
        "FBS_SESSION_MODE",
        "FBS_SESSION_TIME_REFERENCE",
        "FBS_BROKER_UTC_OFFSET",
        "FBS_BLOCK_WEEKENDS",
        "FBS_FAST_PROFILE",
        "FBS_EMA_FAST",
        "FBS_EMA_SLOW",
        "FBS_RSI_PERIOD",
        "FBS_SL_ATR_MULT",
        "FBS_TP_ATR_MULT",
        "FBS_MIN_RR",
        "FBS_AI_MIN_CONFIDENCE",
        "AI_MODEL",
        "AI_BASE_URL",
        "AI_API_KEY",
        "FBS_MT5_LOGIN",
        "FBS_MT5_PASSWORD",
        "FBS_MT5_SERVER",
        "FBS_MT5_PATH",
        "FBS_SIM_BALANCE",
        "FBS_SIM_START_PRICE",
        "FBS_SIM_SPREAD_POINTS",
    ]

    for key in order:
        value = data.get(key)
        if value is None or value == "":
            continue
        # Quote values that may contain spaces/special chars.
        escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
        lines.append('{}="{}"'.format(key, escaped))

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(str(path), 0o600)


def main():
    print("\n=== FBS Trading Setup Assistant ===\n")
    print("Tip: credentials from screenshots are considered exposed.")
    print("Change them and use fresh trading credentials.\n")

    env_path = Path(".fbs_trading.env")

    data = {}
    data["FBS_PROFILE_PRESET"] = ask(
        "Profile preset (xau_scalp_aggressive/xau_scalp_balanced/custom)",
        default="xau_scalp_aggressive",
    )

    simulation_default = True
    data["FBS_SIMULATION_MODE"] = "y" if ask_bool("Enable simulation mode", simulation_default) else "n"
    data["FBS_DRY_RUN"] = "y"

    data["FBS_SYMBOL"] = ask("Symbol", default="XAUUSD")
    data["FBS_TIMEFRAME"] = ask("Timeframe", default="M1")
    data["FBS_BARS"] = ask("Candles", default="500")
    data["FBS_RISK_PCT"] = ask("Risk percent", default="1.0")
    data["FBS_DEVIATION"] = ask("Deviation", default="30")
    data["FBS_MAX_SPREAD_POINTS"] = ask("Max spread points", default="35")
    data["FBS_SESSION_MODE"] = ask(
        "Session mode (off/overlap/london/newyork/london_newyork)",
        default="overlap",
    )
    data["FBS_SESSION_TIME_REFERENCE"] = ask("Session clock (utc/broker)", default="utc")
    data["FBS_BROKER_UTC_OFFSET"] = ask("Broker UTC offset", default="0.0")
    data["FBS_BLOCK_WEEKENDS"] = "y" if ask_bool("Block weekends", True) else "n"

    data["FBS_FAST_PROFILE"] = "y" if ask_bool("Use fast scalp profile", True) else "n"
    data["FBS_EMA_FAST"] = ask("EMA fast", default="7")
    data["FBS_EMA_SLOW"] = ask("EMA slow", default="17")
    data["FBS_RSI_PERIOD"] = ask("RSI period", default="6")
    data["FBS_SL_ATR_MULT"] = ask("SL ATR multiplier", default="0.55")
    data["FBS_TP_ATR_MULT"] = ask("TP ATR multiplier", default="1.35")
    data["FBS_MIN_RR"] = ask("Min risk:reward", default="2.0")
    data["FBS_AI_MIN_CONFIDENCE"] = ask("AI min confidence", default="0.72")

    enable_ai = ask_bool("Enable AI confirmation", False)
    if enable_ai:
        data["AI_MODEL"] = ask("AI model", default="gpt-4o-mini")
        data["AI_BASE_URL"] = ask("AI base URL", default="https://api.openai.com/v1")
        data["AI_API_KEY"] = ask("AI API key", secret=True)

    if data["FBS_SIMULATION_MODE"] == "y":
        data["FBS_SIM_BALANCE"] = ask("Simulation balance", default="10000")
        data["FBS_SIM_START_PRICE"] = ask("Simulation start price", default="2900")
        data["FBS_SIM_SPREAD_POINTS"] = ask("Simulation spread points", default="20")
    else:
        data["FBS_MT5_LOGIN"] = ask("MT5 login (numeric)")
        data["FBS_MT5_PASSWORD"] = ask("MT5 password", secret=True)
        data["FBS_MT5_SERVER"] = ask("MT5 server (example: FBS-Demo)")
        data["FBS_MT5_PATH"] = ask("MT5 terminal path (optional)", allow_empty=True)

    write_env(env_path, data)

    print("\nSaved:", env_path)
    print("Permissions set to 600.")
    print("\nNext steps:")
    print("1) Load env")
    print("   set -a; source ./.fbs_trading.env; set +a")
    print("2) Run from SET")
    print("   sudo -E python3 setoolkit")
    print("   -> choose 3 (Third Party Modules) -> 2 (FBS AI Assistant)")
    print("\nQuick direct run (without SET menu):")
    print("   ./scripts/run_fbs_module_direct.sh")


if __name__ == "__main__":
    main()
